blueprint:
  name: Pilotage chauffage
  description: Gestion des différents modes de chauffage - Stop  Hors-gel  Auto Absent Manuel (Dérogation)
  domain: automation
  input:
    entity_consigne:
      name: Consigne
      description: Champs d'entrée de la température de consigne (input number)
      selector:
        entity:
          domain: input_number
          multiple: false
    entity_derogation:
      name: Durée de la dérogation
      description: Champs d'entrée de la durée de la dérogation (input number)
      selector:
        entity:
          domain: input_number
          multiple: false
    entity_timer_derogation:
      name: Timer de la dérogation
      description: Compteur du temps restant de la dérogation
      selector:
        entity:
          domain: timer
          multiple: false      
    entity_mode:
      name: Sélection du mode
      description: Entité de gestion du mode de gestion du chauffage (input_select)
      selector:
        entity:
          domain: input_select
          multiple: false
    entity_schedule:
      name: Schedules
      description: Entités générées par schedule pour la planification (switch)
      selector:
        entity:
          domain: switch
          multiple: true
    entity_thermostat_tpi:
      name: Thermostat
      description: Entité de gestion du thermostat TPI (automation)
      selector:
        entity:
          domain: automation
          multiple: false
  source_url: https://raw.githubusercontent.com/jbtrystram/chauffage-home-assistant/main/blueprint/chauffage_pilotage.yaml
variables:
  temperature_hg: 8
  temperature_absence: 17
  duree_derog: !input entity_derogation
alias: Pilotage chauffage bureau
description: ''
trigger:
  - platform: state
    entity_id: !input entity_mode
  - platform: event # -- trigger when the derogation timer ended
    id: "timer_finished"
    event_type: timer.finished
    event_data:
      entity_id: !input entity_timer_derogation
  - platform: state # -- trigger when the derogation duration input changed
    id: "duree_derog_changed"
    entity_id: !input entity_derogation
condition: []
action:
  - choose:
      - conditions:   # ----------------- Mode STOP
          - condition: state
            entity_id: !input entity_mode
            state: Stop
        sequence:
          - service: input_number.set_value
            data:
              value: 0
            entity_id: !input entity_consigne
          - service: switch.turn_off
            entity_id: !input entity_schedule
          - service: automation.turn_off
            entity_id: !input entity_thermostat_tpi
          - service: timer.cancel
            entity_id: !input entity_timer_derogation
      - conditions: # ------------------- Mode HORS GEL
          - condition: state
            entity_id: !input entity_mode
            state: Hors-gel
        sequence:
          - service: automation.turn_on
            entity_id: !input entity_thermostat_tpi
          - service: input_number.set_value
            data:
              value: '{{temperature_hg}}'
            entity_id: !input entity_consigne
          - service: switch.turn_off
            entity_id: !input entity_schedule
          - service: timer.cancel
            entity_id: !input entity_timer_derogation
      - conditions: # ------------------- Mode Auto
          - condition: state
            entity_id: !input entity_mode
            state: Auto
        sequence:
          - service: automation.turn_on
            entity_id: !input entity_thermostat_tpi
          - service: switch.turn_on
            entity_id: !input entity_schedule
          - service: timer.cancel
            entity_id: !input entity_timer_derogation
      - conditions: # ------------------- Mode Absent
          - condition: state
            entity_id: !input entity_mode
            state: Absent
        sequence:
          - service: automation.turn_on
            entity_id: !input entity_thermostat_tpi
          - service: input_number.set_value
            data:
              value: '{{temperature_absence}}'
            entity_id: !input entity_consigne
          - service: switch.turn_off
            entity_id: !input entity_schedule
          - service: timer.cancel
            entity_id: !input entity_timer_derogation
      - conditions: # ------------------- Mode Dérogation fini
          - and:  # Timer is finished
            - condition: state
              entity_id: !input entity_mode
              state: Dérogation
            - condition: trigger
              id: "timer_finished"
        sequence:
          # On revient sur le auto quand la dérogation est terminée
          - service: input_select.select_option
            data:
              option: Auto
            target:
              entity_id: !input entity_mode
      - conditions: # ------------------- Mode Dérogation début
          - or:
            - condition: state
              entity_id: !input entity_mode
              state: Dérogation
            - condition: trigger  # Démarrer aussi si la durée de la dérog a changé
              id: "duree_derog_changed"
        sequence:
          - service: switch.turn_off
            entity_id: !input entity_schedule
          - service: automation.turn_on
            entity_id: !input entity_thermostat_tpi
          - service: timer.start
            entity_id: !input entity_timer_derogation
            data_template:
              duration: "{{states[duree_derog].state | int}}:00:00"

    default:
      - service: switch.turn_off
        entity_id: !input entity_schedule
      - service: automation.turn_on
        entity_id: !input entity_thermostat_tpi
mode: restart
